Allow more commands to run with runner

diff --git a/bin/sf b/bin/sf
--- a/bin/sf
+++ b/bin/sf
@@ -1,9 +1,5 @@
 #!/usr/bin/env zsh
 
-if [[ -n "${SF_CONSOLE_RUNNER}" ]]; then
-    exec "${(@s: :)SF_CONSOLE_RUNNER}" bin/console "$@"
-fi
-
 declare -rx app_name="${0##*/}"
 
 main() (
@@ -19,48 +15,20 @@ main() (
 
             shift && exec symfony server:status "$@"
             ;;
+        run)
+            shift && run "$@"
+            ;;
         php)
-            symfony_cli_required
-
-            shift && exec symfony php "$@"
+            shift && run_php "$@"
             ;;
         composer)
-            symfony_cli_required
-
-            shift && exec symfony composer "$@"
+            shift && run_composer "$@"
             ;;
         phpunit)
-            symfony_cli_required
-
-            if [[ ! -f bin/phpunit ]]; then
-                echo 'PHPUnit not found: bin/phpunit' >&2
-                echo '\nInstallation:\n'
-                echo "  ${app_name} composer require --dev phpunit"
-                exit 1
-            fi
-
-            shift && exec symfony php bin/phpunit "$@"
+            shift && run_phpunit "$@"
             ;;
         phive)
-            symfony_cli_required
-
-            local phive="$(find_phive)"
-
-            if [[ -z "${phive}" ]]; then
-                echo 'PHIVE required: https://phar.io/#Install' >&2
-                if command -v brew > /dev/null; then
-                    echo '\nHomebrew:\n'
-                    echo '  brew install phive'
-                fi
-                exit 1
-            fi
-
-            shift && exec symfony php "${phive}" "$@"
-            ;;
-        run)
-            symfony_cli_required
-
-            shift && exec symfony run "$@"
+            shift && run_phive "$@"
             ;;
         psql)
             symfony_cli_required
@@ -79,13 +47,7 @@ main() (
             ;;
     esac
 
-    symfony_console_required
-
-    if command -v symfony >/dev/null; then
-        exec symfony console "$@"
-    fi
-
-    exec bin/console "$@"
+    run_console "$@"
 )
 
 app_new() (
@@ -172,12 +134,115 @@ HELP
     exec php -S "127.0.0.1:${port[2]/=}" -t "${root[2]/=}"
 )
 
-symfony_console_required() {
-    [[ -f bin/console ]] && return
+run() {
+    if [[ -n "${SF_CONSOLE_RUNNER}" ]]; then
+       exec "${(@s: :)SF_CONSOLE_RUNNER}" "$@"
+    fi
 
-    echo 'Symfony console not found: bin/console' >&2
-    exit 1
+    if which symfony >/dev/null; then
+        exec symfony run "$@"
+    fi
+
+    exec "$@"
 }
+
+run_php() {
+    if [[ -n "${SF_CONSOLE_RUNNER}" ]]; then
+       exec "${(@s: :)SF_CONSOLE_RUNNER}" php "$@"
+    fi
+
+    if which symfony >/dev/null; then
+        exec symfony php "$@"
+    fi
+
+    exec php "$@"
+}
+
+run_composer() {
+    if [[ -n "${SF_CONSOLE_RUNNER}" ]]; then
+       exec "${(@s: :)SF_CONSOLE_RUNNER}" composer "$@"
+    fi
+
+    if which symfony >/dev/null; then
+        exec symfony composer "$@"
+    fi
+
+    exec composer "$@"
+}
+
+run_phpunit() {
+    if [[ ! -f bin/phpunit ]]; then
+        echo 'PHPUnit not found: bin/phpunit' >&2
+        echo '\nInstallation:\n'
+        echo "  ${app_name} composer require --dev phpunit"
+        exit 1
+    fi
+
+    run_php bin/phpunit "$@"
+}
+
+run_console() {
+    if [[ ! -f bin/console ]]; then
+        echo 'Symfony console not found: bin/console' >&2
+        exit 1
+    fi
+
+    if [[ -n "${SF_CONSOLE_RUNNER}" ]]; then
+       exec "${(@s: :)SF_CONSOLE_RUNNER}" bin/console "$@"
+    fi
+
+    if which symfony >/dev/null; then
+        exec symfony console "$@"
+    fi
+
+    exec bin/console "$@"
+}
+
+run_phive() {
+    local phive="$(find_phive)"
+
+    if [[ -z "${phive}" ]]; then
+        if [[ -n "${SF_CONSOLE_RUNNER}" ]]; then
+            run phive "$@"
+        fi
+
+        echo 'PHIVE required: https://phar.io/#Install' >&2
+        if command -v brew > /dev/null; then
+            echo '\nHomebrew:\n'
+            echo '  brew install phive'
+        fi
+        exit 1
+    fi
+
+    run_php "${phive}" "$@"
+}
+
+find_phive() {
+    local phive="${PWD}/phive.phar"
+    if [[ -f "${phive}" ]]; then
+        echo "${phive}"
+        return
+    fi
+
+    phive="${PWD}/bin/phive"
+    if [[ -f "${phive}" ]]; then
+        echo "${phive}"
+        return
+    fi
+
+    if [[ -n "${SF_CONSOLE_RUNNER}" ]]; then
+        return 1
+    fi
+
+    phive="$(which phive 2>/dev/null)"
+    if [[ $? -eq 0 && -f "${phive}" ]]; then
+        echo "${phive}"
+        return
+    fi
+
+    return 1
+}
+
 
 symfony_cli_required() {
     command -v symfony >/dev/null && return
@@ -196,28 +261,6 @@ symfony_cli_required() {
     fi
 
     exit 1
-}
-
-find_phive() {
-    local phive="${PWD}/phive.phar"
-    if [[ -f "${phive}" ]]; then
-        echo "${phive}"
-        return
-    fi
-
-    phive="${PWD}/bin/phive"
-    if [[ -f "${phive}" ]]; then
-        echo "${phive}"
-        return
-    fi
-
-    phive="$(which phive 2>/dev/null)"
-    if [[ $? -eq 0 && -f "${phive}" ]]; then
-        echo "${phive}"
-        return
-    fi
-
-    return 1
 }
 
 main "$@"
